// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuEkY40s003e5_xgFQ_sk2OsHT0EnMZcA',
    appId: '1:142808937203:web:bc9a36e49ba98a9000fd86',
    messagingSenderId: '142808937203',
    projectId: 'fir-bloc-75738',
    authDomain: 'fir-bloc-75738.firebaseapp.com',
    storageBucket: 'fir-bloc-75738.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDimA8y_ZC02JMg2CwGHG-cyKNnfxlN6yw',
    appId: '1:142808937203:android:71b275d242b08a4600fd86',
    messagingSenderId: '142808937203',
    projectId: 'fir-bloc-75738',
    storageBucket: 'fir-bloc-75738.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpeSKIaLkV0CC9bx5L_LOmF4pP5YV3sKY',
    appId: '1:142808937203:ios:3b97c8e81ed18f4100fd86',
    messagingSenderId: '142808937203',
    projectId: 'fir-bloc-75738',
    storageBucket: 'fir-bloc-75738.appspot.com',
    iosBundleId: 'com.example.blocTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpeSKIaLkV0CC9bx5L_LOmF4pP5YV3sKY',
    appId: '1:142808937203:ios:07cc2f8bd3fd15ee00fd86',
    messagingSenderId: '142808937203',
    projectId: 'fir-bloc-75738',
    storageBucket: 'fir-bloc-75738.appspot.com',
    iosBundleId: 'com.example.blocTest.RunnerTests',
  );
}
